### PR TITLE
Fix Integration tests to import module directly

### LINKED ISSUE #3: Integration tests does not import module directly
## Bug

Integration tests does not import module directly.

## Expected 

Integration tests does import module directly.

### PR DESCRIPTION
**Pull request by leojonathanoh**
Fixes #3

### CODE REVIEW

**Comment by joeltimothyoh** [comment]
This is unneeded if the entrypoint script `Invoke-PSModulePublisher.ps1` is used to run build and test stages. The module is imported before tests are run.

**Review by joeltimothyoh — CHANGES_REQUESTED** [review]
As per https://github.com/startersclan/Compile-SourceScript/pull/5#issuecomment-619669148

**Comment by leojonathanoh** [comment]
Developers lose the ability to run integration tests directly on their machines.

**Comment by joeltimothyoh** [comment]
> 
> 
> Developers lose the ability to run integration tests directly on their machines.

That's exactly the problem the entrypoint script [`Invoke-PSModulePublisher.ps1`](https://github.com/theohbrothers/PSModulePublisher/tree/v0.3.2#development) aims to solve in development environments.

**Comment by leojonathanoh** [comment]
ok will close

**Pull request closed without merging**
